baseURL = 'https://winnipeg-cpp.github.io/website/'
canonifyURLs = true
languageCode = 'en-us'
timeZone = 'America/Winnipeg'
title = 'Winnipeg C++ Developers'
theme = 'PaperMod'

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML', 'RSS']

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  [params.logo]
    logoText = 'Winnipeg C++ Developers'
    # Uncomment and add path to use an image instead of text
    # logo = '/images/logo.png'
    # logoHeight = 30

[[menu.main]]
  name = 'Posts'
  url = 'posts/'
  weight = 10

[[menu.main]]
  name = 'GitHub'
  url = 'https://github.com/winnipeg-cpp'
  weight = 20

[[menu.main]]
  name = 'RSS'
  url = 'index.xml'
  weight = 30

[[params.socialIcons]]
  name = 'github'
  url = 'https://github.com/winnipeg-cpp'

[[params.socialIcons]]
  name = 'eventbrite'
  url = 'https://www.eventbrite.ca/o/braden-ganetsky-77752664253'
