baseURL = 'https://winnipeg-cpp.github.io/website/'
canonifyURLs = true
languageCode = 'en-us'
timeZone = 'America/Winnipeg'
title = 'Winnipeg C++ Developers'
theme = 'PaperMod'

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML', 'RSS']

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  [params.logo]
    logoText = 'Winnipeg C++ Developers'
    # Uncomment and add path to use an image instead of text
    # logo = '/images/logo.png'
    # logoHeight = 30

[[menu.main]]
  name = 'Posts'
  url = 'posts/'
  weight = 10

[[menu.main]]
  name = 'GitHub'
  url = 'https://github.com/winnipeg-cpp'
  weight = 20

[[menu.main]]
  name = 'RSS'
  url = 'index.xml'
  weight = 30

[[params.socialIcons]]
  name = 'github'
  url = 'https://github.com/winnipeg-cpp'

[[params.socialIcons]]
  name = 'eventbrite'
  url = 'https://www.eventbrite.ca/o/braden-ganetsky-77752664253'

# Newsletter subscription configuration (disabled by default)
# Uncomment and configure to enable email subscriptions
# See docs/NEWSLETTER_SETUP.md for detailed setup instructions
#
# [params.newsletter]
#   enabled = true
#   provider = "buttondown"  # Options: "buttondown", "mailchimp", "custom"
#   title = "Subscribe to our newsletter"
#   description = "Get notified when we publish new posts about C++ development in Winnipeg"
#   placeholder = "your@email.com"
#   buttonText = "Subscribe"
#   note = "We respect your privacy. Unsubscribe at any time."
#
#   # For Buttondown (recommended - free, privacy-focused)
#   [params.newsletter.buttondown]
#     username = "winnipeg-cpp"  # Your Buttondown username
#
#   # For Mailchimp (uncomment if using Mailchimp instead)
#   # [params.newsletter.mailchimp]
#   #   actionUrl = "https://yourname.us1.list-manage.com/subscribe/post?u=xxx&id=yyy"
#   #   botField = "b_xxx_yyy"
#
#   # For custom provider (uncomment if using another service)
#   # [params.newsletter.custom]
#   #   actionUrl = "https://your-service.com/subscribe"
#   #   emailFieldName = "email"
